#ifndef AST_KIND_HPP
#define AST_KIND_HPP

namespace ast {
enum class Kind {
  UNDEF,
  ARITHMETIC_EXPR_LVL1,
  ARITHMETIC_EXPR_LVL2,
  LOGIC_EXPR_LVL1,
  ARITHMETIC_EXPRESSION,
  LOGIC_EXPRESSION,
  L_VALUE,
  LOGIC_CONSTANT,
  R_VALUE,
  ARITHMETIC_EXPR_LVL5,
  ARITHMETIC_EXPRESSIONS_COMPARISON,
  REAL,
  PROGRAM,
  LOGIC_TERM,
  ARITHMETIC_EXPR_LVL4,
  ARITHMETIC_CONSTANT,
  ARITHMETIC_TERM,
  INTEGER,
  ARITHMETIC_EXPR_LVL3,
  LOGIC_EXPR_LVL2,
  IDENTIFIER,

};
}  // namespace ast

#endif  // AST_KIND_HPP